name: dslink_zoneminder
description: Zoneminder DSLink
environment:
  sdk: ">=1.11.0 <2.0.0"
dependencies:
  dslink: '^0.5.8'
  http: '^0.11.3+3'
  quiver: '^0.21.4'
dev_dependencies:  
  test: '^0.12.11+2'
