name: dslink_zoneminder
description: Zoneminder DSLink
environment:
  sdk: ">=1.11.0 <2.0.0"
dependencies:
  dslink:
    git: 'https://github.com/IOT-DSA/sdk-dslink-dart'
  http: '^0.11.3+3'
  quiver: '^0.21.4'
  collection: '^1.4.0'
  typed_data: '^1.1.3'
dev_dependencies:
  test: '^0.12.11+2'
